// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using SportSys.Database.Context;

#nullable disable

namespace SportSys.Database.Migrations
{
    [DbContext(typeof(SportSysDbContext))]
    [Migration("20260907051842_HrCoach")]
    partial class HrCoach
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("InventoryItemSeq", "inventory");

            modelBuilder.HasSequence<int>("SportEventSeq", "sport");

            modelBuilder.Entity("SportSys.Database.Models.dbo.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer", "dbo");
                });

            modelBuilder.Entity("SportSys.Database.Models.dboSchema.CoachRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CoachRole", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hlavní"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Asistent"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Obránci"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gólmani"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fyzio"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kondiční"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhotoFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Coach", "hr");
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.CoachContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<byte>("ContractType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_CoachContract_IsActive");

                    b.Property<decimal>("RewardAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CoachId", "SeasonId" }, "IX_CoachContract_Coach_Season");

                    b.HasIndex(new[] { "SeasonId" }, "IX_CoachContract_Season");

                    b.ToTable("CoachContract", "hr", t =>
                        {
                            t.HasCheckConstraint("CK_CoachContract_ContractType", "[ContractType] IN (1, 2)");

                            t.HasCheckConstraint("CK_CoachContract_RewardAmount", "[RewardAmount] >= 0");

                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");

                            t.Property("SeasonId")
                                .HasColumnName("Season_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.CoachLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("CoachLicenseTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CoachLicenseTypeId" }, "IX_CoachLicense_CoachLicenseType");

                    b.HasIndex(new[] { "CoachId", "ValidFrom", "ValidTo" }, "IX_CoachLicense_Coach_Validity");

                    b.ToTable("CoachLicense", "hr", t =>
                        {
                            t.HasCheckConstraint("CK_CoachLicense_Validity", "[ValidTo] IS NULL OR [ValidTo] >= [ValidFrom]");

                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");

                            t.Property("CoachLicenseTypeId")
                                .HasColumnName("CoachLicenseType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.CoachLicenseType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "UX_CoachLicenseType_Code")
                        .IsUnique();

                    b.ToTable("CoachLicenseType", "hr");
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.CoachSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BankAccountPrefix")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("HealthInsuranceCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CoachId", "ValidFrom", "ValidTo" }, "IX_CoachSetting_Coach_Validity");

                    b.ToTable("CoachSetting", "hr", t =>
                        {
                            t.HasCheckConstraint("CK_CoachSetting_Validity", "[ValidTo] IS NULL OR [ValidTo] >= [ValidFrom]");

                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", "identity");
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleClaim", "identity", t =>
                        {
                            t.Property("RoleId")
                                .HasColumnName("Role_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EntraOid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntraTenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocalAccount")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", "identity");
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaim", "identity", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("User_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogin", "identity", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("User_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRole", "identity", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("User_Id");

                            t.Property("RoleId")
                                .HasColumnName("Role_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", "identity", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("User_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryKinds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryKindJson");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category", "inventory", t =>
                        {
                            t.Property("ParentCategoryId")
                                .HasColumnName("ParentCategory_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventoryCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("Found")
                        .HasColumnType("bit");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("InventorySessionId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InventorySessionId", "InventoryItemId" }, "UX_InventoryCheck_SessionItem")
                        .IsUnique();

                    b.ToTable("InventoryCheck", "inventory", t =>
                        {
                            t.Property("ActualLocationId")
                                .HasColumnName("ActualLocation_Id");

                            t.Property("CheckedByUserId")
                                .HasColumnName("CheckedByUser_Id");

                            t.Property("InventorySessionId")
                                .HasColumnName("InventorySession_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NEXT VALUE FOR [inventory].[InventoryItemSeq])");

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("AcquisitionPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("AssignedLocationId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QRCodeValue")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventoryItemPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseDocumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("PurchaseDocumentId");

                    b.ToTable("InventoryItemPurchase", "inventory", t =>
                        {
                            t.Property("PurchaseDocumentId")
                                .HasColumnName("PurchaseDocument_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventorySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InventorySession", "inventory");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InventoryItemId", "TransactionDate" }, "IX_InventoryTransaction_ItemDate");

                    b.ToTable("InventoryTransaction", "inventory", t =>
                        {
                            t.Property("TransactionTypeId")
                                .HasColumnName("TransactionType_Id");

                            t.Property("UserId")
                                .HasColumnName("User_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.ItemKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemKind", "inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dětské"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Youth"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Juniorské"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Seniorské"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dámské"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pánské"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Unisex"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.ItemLocationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("NewLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PreviousLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InventoryItemId", "ChangedAt" }, "IX_ItemLocationHistory_ItemDate");

                    b.ToTable("ItemLocationHistory", "inventory", t =>
                        {
                            t.Property("ChangedByUserId")
                                .HasColumnName("ChangedByUser_Id");

                            t.Property("NewLocationId")
                                .HasColumnName("NewLocation_Id");

                            t.Property("PreviousLocationId")
                                .HasColumnName("PreviousLocation_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ExpectedReturnDate")
                        .HasColumnType("date");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("LoanDate")
                        .HasColumnType("date");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("ReturnedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loan", "inventory", t =>
                        {
                            t.Property("MemberId")
                                .HasColumnName("Member_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Location", "inventory");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.PurchaseDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseDocument", "inventory");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionType", "inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nákup"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zapůjčení"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vrácení"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Přesun"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zahájení opravy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ukončení opravy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Inventura"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ztráta"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Vyřazení"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.CoachTraining", b =>
                {
                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("", "DF_CoachTraining_Note");

                    b.HasKey("CoachId", "TrainingId", "ParticipationTypeId");

                    b.ToTable("CoachTraining", "sport", t =>
                        {
                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");

                            t.Property("TrainingId")
                                .HasColumnName("Training_Id");

                            t.Property("ParticipationTypeId")
                                .HasColumnName("ParticipationType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.CoachTrainingEntitlement", b =>
                {
                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingEntitlementId")
                        .HasColumnType("int");

                    b.Property<int>("CoachRoleId")
                        .HasColumnType("int");

                    b.HasKey("CoachId", "TrainingEntitlementId", "CoachRoleId");

                    b.ToTable("CoachTrainingEntitlement", "sport", t =>
                        {
                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");

                            t.Property("TrainingEntitlementId")
                                .HasColumnName("TrainingEntitlement_Id");

                            t.Property("CoachRoleId")
                                .HasColumnName("CoachRole_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.CoachTrainingPlan", b =>
                {
                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("CoachId", "TrainingPlanId", "ValidFrom", "ValidTo");

                    b.HasIndex(new[] { "CoachId", "ValidFrom", "ValidTo" }, "IX_CoachTraining_Coach_Date");

                    b.HasIndex(new[] { "TrainingPlanId", "ValidFrom", "ValidTo" }, "IX_CoachTraining_Training_Date");

                    b.ToTable("CoachTrainingPlan", "sport", t =>
                        {
                            t.Property("CoachId")
                                .HasColumnName("Coach_Id");

                            t.Property("TrainingPlanId")
                                .HasColumnName("TrainingPlan_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.IceRink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_IceRink_IsActive");

                    b.Property<Geometry>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("", "DF_IceRink_ZipCode");

                    b.HasKey("Id");

                    b.ToTable("IceRink", "sport");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Season_IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Season", "sport");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.SeasonCategory", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BirthYears")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasDefaultValue("[]", "DF_SeasonCategory_BirthYears");

                    b.Property<string>("CompetitionCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("", "DF_SeasonCategory_CompetitionCode");

                    b.Property<string>("CompetitionTeamName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("", "DF_SeasonCategory_CompetitionTeamName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_SeasonCategory_IsActive");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "Name");

                    b.ToTable("SeasonCategory", "sport", t =>
                        {
                            t.Property("SeasonId")
                                .HasColumnName("Season_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.SportEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NEXT VALUE FOR [sport].[SportEventSeq])");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SeasonCategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SeasonCategory_Name");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("SeasonCategory_Season_Id");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("HomeIceRinkId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Team_IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Team", "sport", t =>
                        {
                            t.Property("HomeIceRinkId")
                                .HasColumnName("HomeIceRink_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingEntitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DurationHours")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("SeasonCategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.Property<int>("TrainingPhaseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrainingEntitlement", "sport", t =>
                        {
                            t.Property("SeasonCategoryName")
                                .HasColumnName("SeasonCategory_Name");

                            t.Property("SeasonId")
                                .HasColumnName("SeasonCategory_Season_Id");

                            t.Property("TrainingPhaseId")
                                .HasColumnName("TrainingPhase_Id");

                            t.Property("TrainingTypeId")
                                .HasColumnName("TrainingType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "TrainingId");

                    b.HasIndex(new[] { "TrainingId" }, "UX_TrainingGroup_TrainingId")
                        .IsUnique();

                    b.ToTable("TrainingGroup", "sport", t =>
                        {
                            t.Property("TrainingId")
                                .HasColumnName("Training_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("DurationMinutes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(datediff(minute,[TimeFrom],[TimeTo]))", true);

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeasonCategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("TimeTo")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.Property<int>("TrainingPhaseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrainingPlan", "sport", t =>
                        {
                            t.Property("SeasonCategoryName")
                                .HasColumnName("SeasonCategory_Name");

                            t.Property("SeasonId")
                                .HasColumnName("SeasonCategory_Season_Id");

                            t.Property("TrainingPhaseId")
                                .HasColumnName("TrainingPhase_Id");

                            t.Property("TrainingTypeId")
                                .HasColumnName("TrainingType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingPlanGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "TrainingPlanId");

                    b.HasIndex(new[] { "TrainingPlanId" }, "UX_TrainingPlanGroup_TrainingPlanId")
                        .IsUnique();

                    b.ToTable("TrainingPlanGroup", "sport", t =>
                        {
                            t.Property("TrainingPlanId")
                                .HasColumnName("TrainingPlan_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.MatchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MatchType", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ligový zápas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Příprava"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Turnaj"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.ParticipationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ParticipationType", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Účast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bez reakce"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Neúčast"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Spojený trénink"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Neúčast - jiný trénink"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TrainingPhase", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Přípravné období"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Předzávodní období"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Závodní období"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Přechodné (regenerační) období"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TrainingState", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Plán"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Potvrzený KIS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jen KIS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Změna času"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zrušený"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Změna termínu"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Porucha ZS"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TrainingType", "sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Suchá příprava"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Led"
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Asset", b =>
                {
                    b.HasBaseType("SportSys.Database.Models.inventory.InventoryItem");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("WarrantyUntil")
                        .HasColumnType("date");

                    b.ToTable("Asset", "inventory");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Equipment", b =>
                {
                    b.HasBaseType("SportSys.Database.Models.inventory.InventoryItem");

                    b.Property<int?>("ItemKindId")
                        .HasColumnType("int")
                        .HasColumnName("ItemKindId");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Equipment", "inventory", t =>
                        {
                            t.Property("ItemKindId")
                                .HasColumnName("ItemKind_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Match", b =>
                {
                    b.HasBaseType("SportSys.Database.Models.sport.SportEvent");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("IceRinkId")
                        .HasColumnType("int");

                    b.Property<string>("MatchCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("MatchTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("json")
                        .HasColumnName("Result");

                    b.ToTable("Match", "sport", t =>
                        {
                            t.Property("SeasonCategoryName")
                                .HasColumnName("SeasonCategory_Name");

                            t.Property("SeasonId")
                                .HasColumnName("SeasonCategory_Season_Id");

                            t.Property("AwayTeamId")
                                .HasColumnName("AwayTeam_Id");

                            t.Property("HomeTeamId")
                                .HasColumnName("HomeTeam_Id");

                            t.Property("IceRinkId")
                                .HasColumnName("IceRink_Id");

                            t.Property("MatchTypeId")
                                .HasColumnName("MatchType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Training", b =>
                {
                    b.HasBaseType("SportSys.Database.Models.sport.SportEvent");

                    b.Property<int?>("DurationMinutes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(datediff(minute,[TimeFrom],[TimeTo]))", true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeOnly>("TimeTo")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<int>("TrainingPhaseId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingPlanId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingStateId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.ToTable("Training", "sport", t =>
                        {
                            t.Property("SeasonCategoryName")
                                .HasColumnName("SeasonCategory_Name");

                            t.Property("SeasonId")
                                .HasColumnName("SeasonCategory_Season_Id");

                            t.Property("TrainingPhaseId")
                                .HasColumnName("TrainingPhase_Id");

                            t.Property("TrainingPlanId")
                                .HasColumnName("TrainingPlan_Id");

                            t.Property("TrainingStateId")
                                .HasColumnName("TrainingState_Id");

                            t.Property("TrainingTypeId")
                                .HasColumnName("TrainingType_Id");
                        });
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.CoachContract", b =>
                {
                    b.HasOne("SportSys.Database.Models.hr.Coach", "Coach")
                        .WithMany("Contracts")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.Season", "Season")
                        .WithMany("CoachContracts")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.CoachLicense", b =>
                {
                    b.HasOne("SportSys.Database.Models.hr.Coach", "Coach")
                        .WithMany("Licenses")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.hr.CoachLicenseType", "CoachLicenseType")
                        .WithMany("Licenses")
                        .HasForeignKey("CoachLicenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("CoachLicenseType");
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.CoachSetting", b =>
                {
                    b.HasOne("SportSys.Database.Models.hr.Coach", "Coach")
                        .WithMany("Settings")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.RoleClaim", b =>
                {
                    b.HasOne("SportSys.Database.Models.identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.UserClaim", b =>
                {
                    b.HasOne("SportSys.Database.Models.identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.UserLogin", b =>
                {
                    b.HasOne("SportSys.Database.Models.identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.UserRole", b =>
                {
                    b.HasOne("SportSys.Database.Models.identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportSys.Database.Models.identity.UserToken", b =>
                {
                    b.HasOne("SportSys.Database.Models.identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Category", b =>
                {
                    b.HasOne("SportSys.Database.Models.inventory.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventoryCheck", b =>
                {
                    b.HasOne("SportSys.Database.Models.inventory.Location", "ActualLocation")
                        .WithMany()
                        .HasForeignKey("ActualLocationId");

                    b.HasOne("SportSys.Database.Models.identity.User", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId");

                    b.HasOne("SportSys.Database.Models.inventory.InventorySession", "InventorySession")
                        .WithMany("InventoryChecks")
                        .HasForeignKey("InventorySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualLocation");

                    b.Navigation("CheckedByUser");

                    b.Navigation("InventorySession");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventoryItem", b =>
                {
                    b.HasOne("SportSys.Database.Models.inventory.Location", "AssignedLocation")
                        .WithMany("AssignedInventoryItems")
                        .HasForeignKey("AssignedLocationId");

                    b.HasOne("SportSys.Database.Models.inventory.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.inventory.Location", "CurrentLocation")
                        .WithMany("CurrentInventoryItems")
                        .HasForeignKey("CurrentLocationId");

                    b.HasOne("SportSys.Database.Models.dbo.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("AssignedLocation");

                    b.Navigation("Category");

                    b.Navigation("CurrentLocation");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventoryItemPurchase", b =>
                {
                    b.HasOne("SportSys.Database.Models.inventory.PurchaseDocument", "PurchaseDocument")
                        .WithMany("InventoryItemPurchases")
                        .HasForeignKey("PurchaseDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseDocument");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventoryTransaction", b =>
                {
                    b.HasOne("SportSys.Database.Models.inventory.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.ItemLocationHistory", b =>
                {
                    b.HasOne("SportSys.Database.Models.identity.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId");

                    b.HasOne("SportSys.Database.Models.inventory.Location", "NewLocation")
                        .WithMany()
                        .HasForeignKey("NewLocationId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.inventory.Location", "PreviousLocation")
                        .WithMany()
                        .HasForeignKey("PreviousLocationId");

                    b.Navigation("ChangedByUser");

                    b.Navigation("NewLocation");

                    b.Navigation("PreviousLocation");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Loan", b =>
                {
                    b.HasOne("SportSys.Database.Models.identity.User", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.CoachTraining", b =>
                {
                    b.HasOne("SportSys.Database.Models.hr.Coach", "Coach")
                        .WithMany("CoachTrainings")
                        .HasForeignKey("CoachId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.ParticipationType", "ParticipationType")
                        .WithMany("CoachTrainings")
                        .HasForeignKey("ParticipationTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.Training", "Training")
                        .WithMany("CoachTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("ParticipationType");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.CoachTrainingEntitlement", b =>
                {
                    b.HasOne("SportSys.Database.Models.hr.Coach", "Coach")
                        .WithMany("CoachTrainingEntitlementCoaches")
                        .HasForeignKey("CoachId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.dboSchema.CoachRole", "CoachRole")
                        .WithMany("CoachTrainingEntitlementCoachRoles")
                        .HasForeignKey("CoachRoleId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.TrainingEntitlement", "TrainingEntitlement")
                        .WithMany("CoachTrainingEntitlements")
                        .HasForeignKey("TrainingEntitlementId")
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("CoachRole");

                    b.Navigation("TrainingEntitlement");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.CoachTrainingPlan", b =>
                {
                    b.HasOne("SportSys.Database.Models.hr.Coach", "Coach")
                        .WithMany("CoachTrainingPlans")
                        .HasForeignKey("CoachId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.TrainingPlan", "TrainingPlan")
                        .WithMany("CoachTrainingPlans")
                        .HasForeignKey("TrainingPlanId")
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.SeasonCategory", b =>
                {
                    b.HasOne("SportSys.Database.Models.sport.Season", "Season")
                        .WithMany("SeasonCategories")
                        .HasForeignKey("SeasonId")
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Team", b =>
                {
                    b.HasOne("SportSys.Database.Models.sport.IceRink", "HomeIceRink")
                        .WithMany("Teams")
                        .HasForeignKey("HomeIceRinkId");

                    b.Navigation("HomeIceRink");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingEntitlement", b =>
                {
                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingPhase", "TrainingPhase")
                        .WithMany("TrainingEntitlements")
                        .HasForeignKey("TrainingPhaseId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingType", "TrainingType")
                        .WithMany("TrainingEntitlements")
                        .HasForeignKey("TrainingTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.SeasonCategory", "SeasonCategory")
                        .WithMany("TrainingEntitlements")
                        .HasForeignKey("SeasonId", "SeasonCategoryName")
                        .IsRequired();

                    b.Navigation("SeasonCategory");

                    b.Navigation("TrainingPhase");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingGroup", b =>
                {
                    b.HasOne("SportSys.Database.Models.sport.Training", "Training")
                        .WithOne("GroupMembership")
                        .HasForeignKey("SportSys.Database.Models.sport.TrainingGroup", "TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingPlan", b =>
                {
                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingPhase", "TrainingPhase")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("TrainingPhaseId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingType", "TrainingType")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("TrainingTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.SeasonCategory", "SeasonCategory")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("SeasonId", "SeasonCategoryName")
                        .IsRequired();

                    b.Navigation("SeasonCategory");

                    b.Navigation("TrainingPhase");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingPlanGroup", b =>
                {
                    b.HasOne("SportSys.Database.Models.sport.TrainingPlan", "TrainingPlan")
                        .WithOne("GroupMembership")
                        .HasForeignKey("SportSys.Database.Models.sport.TrainingPlanGroup", "TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Equipment", b =>
                {
                    b.HasOne("SportSys.Database.Models.inventory.ItemKind", "ItemKind")
                        .WithMany()
                        .HasForeignKey("ItemKindId");

                    b.Navigation("ItemKind");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Match", b =>
                {
                    b.HasOne("SportSys.Database.Models.sport.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.IceRink", "IceRink")
                        .WithMany("Matches")
                        .HasForeignKey("IceRinkId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.MatchType", "MatchType")
                        .WithMany("Matches")
                        .HasForeignKey("MatchTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.SeasonCategory", "SeasonCategory")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId", "SeasonCategoryName")
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("IceRink");

                    b.Navigation("MatchType");

                    b.Navigation("Season");

                    b.Navigation("SeasonCategory");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Training", b =>
                {
                    b.HasOne("SportSys.Database.Models.sport.Season", "Season")
                        .WithMany("Training")
                        .HasForeignKey("SeasonId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingPhase", "TrainingPhase")
                        .WithMany("Training")
                        .HasForeignKey("TrainingPhaseId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.TrainingPlan", "TrainingPlan")
                        .WithMany("Training")
                        .HasForeignKey("TrainingPlanId");

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingState", "TrainingState")
                        .WithMany("Training")
                        .HasForeignKey("TrainingStateId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sportSchema.TrainingType", "TrainingType")
                        .WithMany("Training")
                        .HasForeignKey("TrainingTypeId")
                        .IsRequired();

                    b.HasOne("SportSys.Database.Models.sport.SeasonCategory", "SeasonCategory")
                        .WithMany("Training")
                        .HasForeignKey("SeasonId", "SeasonCategoryName")
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("SeasonCategory");

                    b.Navigation("TrainingPhase");

                    b.Navigation("TrainingPlan");

                    b.Navigation("TrainingState");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("SportSys.Database.Models.dboSchema.CoachRole", b =>
                {
                    b.Navigation("CoachTrainingEntitlementCoachRoles");
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.Coach", b =>
                {
                    b.Navigation("CoachTrainingEntitlementCoaches");

                    b.Navigation("CoachTrainingPlans");

                    b.Navigation("CoachTrainings");

                    b.Navigation("Contracts");

                    b.Navigation("Licenses");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("SportSys.Database.Models.hr.CoachLicenseType", b =>
                {
                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Category", b =>
                {
                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.InventorySession", b =>
                {
                    b.Navigation("InventoryChecks");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.Location", b =>
                {
                    b.Navigation("AssignedInventoryItems");

                    b.Navigation("CurrentInventoryItems");
                });

            modelBuilder.Entity("SportSys.Database.Models.inventory.PurchaseDocument", b =>
                {
                    b.Navigation("InventoryItemPurchases");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.IceRink", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Season", b =>
                {
                    b.Navigation("CoachContracts");

                    b.Navigation("Matches");

                    b.Navigation("SeasonCategories");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.SeasonCategory", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Training");

                    b.Navigation("TrainingEntitlements");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingEntitlement", b =>
                {
                    b.Navigation("CoachTrainingEntitlements");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.TrainingPlan", b =>
                {
                    b.Navigation("CoachTrainingPlans");

                    b.Navigation("GroupMembership");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.MatchType", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.ParticipationType", b =>
                {
                    b.Navigation("CoachTrainings");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingPhase", b =>
                {
                    b.Navigation("Training");

                    b.Navigation("TrainingEntitlements");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingState", b =>
                {
                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportSys.Database.Models.sportSchema.TrainingType", b =>
                {
                    b.Navigation("Training");

                    b.Navigation("TrainingEntitlements");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("SportSys.Database.Models.sport.Training", b =>
                {
                    b.Navigation("CoachTrainings");

                    b.Navigation("GroupMembership");
                });
#pragma warning restore 612, 618
        }
    }
}
